# The IMPORTANCE_### files are generated by model_xgboost_ajp.R

files <- list.files(pattern="*IMPORTANCE.*.RData")
outfile = "project/Santander/reports/feature-importance-xgboost.txt"
write("These are the feature importances generated by XGBoost for each product\n\n",file=outfile)
for (file in files){
  load(file)
  feature <- gsub("IMPORTANCE\\_|\\.RData","",file)
  write(paste("Feature importance for",feature,"\n"),file=outfile,append=TRUE)
  write.table(imp,file=outfile,append=TRUE)
  write("\n",file=outfile,append=TRUE)
  write(paste(rep("-",100),collapse=""),file=outfile,append=TRUE)
  write("\n",file=outfile,append=TRUE)
}